"""add user preferences, goals table, memory importance

Revision ID: 6ce8d55f3a62
Revises: 954ee9a91349
Create Date: 2026-09-07 09:57:54.882559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ce8d55f3a62'
down_revision: Union[str, Sequence[str], None] = '954ee9a91349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed')", name='valid_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('memories', sa.Column('importance', sa.Integer(), server_default='3', nullable=False))
    op.create_check_constraint('valid_importance_range', 'memories', 'importance BETWEEN 1 AND 5')
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()),server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_constraint('valid_importance_range', 'memories', type_='check')
    op.drop_column('memories', 'importance')
    op.drop_table('goals')
    # ### end Alembic commands ###
