"""fix message conversation id

Revision ID: d05bbb7b7235
Revises: 9312622c2dee
Create Date: 2026-09-02 09:04:40.194036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05bbb7b7235'
down_revision: Union[str, Sequence[str], None] = '9312622c2dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('messages_Conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('messages', 'Conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('Conversation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_Conversation_id_fkey'), 'messages', 'conversations', ['Conversation_id'], ['id'])
    op.drop_column('messages', 'conversation_id')
    # ### end Alembic commands ###
